version: '3'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    networks:
      - mynetwork
    depends_on:
      - cassandra
  cassandra:
    image: cassandra:latest
    ports:
      - "9042:9042"
    networks:
      - mynetwork

networks:
  mynetwork: